// <auto-generated />
namespace Lab6KPZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Migrrration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migrrration));
        
        string IMigrationMetadata.Id
        {
            get { return "202112030055178_Migrrration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
